/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CircuitsRouteImport } from './routes/circuits'
import { Route as HousesRouteImport } from './routes/houses'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PlayRouteImport } from './routes/play'
import { Route as RevealRouteImport } from './routes/reveal'
import { Route as HousesIndexRouteImport } from './routes/houses.index'
import { Route as HousesIdRouteImport } from './routes/houses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsRoute = CircuitsRouteImport.update({
  id: '/circuits',
  path: '/circuits',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRoute = HousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const RevealRoute = RevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesIndexRoute = HousesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HousesRoute,
} as any)
const HousesIdRoute = HousesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HousesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/circuits': typeof CircuitsRoute
  '/houses': typeof HousesRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/play': typeof PlayRoute
  '/reveal': typeof RevealRoute
  '/houses/$id': typeof HousesIdRoute
  '/houses/': typeof HousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/circuits': typeof CircuitsRoute
  '/methodology': typeof MethodologyRoute
  '/play': typeof PlayRoute
  '/reveal': typeof RevealRoute
  '/houses/$id': typeof HousesIdRoute
  '/houses': typeof HousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/circuits': typeof CircuitsRoute
  '/houses': typeof HousesRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/play': typeof PlayRoute
  '/reveal': typeof RevealRoute
  '/houses/$id': typeof HousesIdRoute
  '/houses/': typeof HousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/circuits'
    | '/houses'
    | '/methodology'
    | '/play'
    | '/reveal'
    | '/houses/$id'
    | '/houses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/circuits'
    | '/methodology'
    | '/play'
    | '/reveal'
    | '/houses/$id'
    | '/houses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/circuits'
    | '/houses'
    | '/methodology'
    | '/play'
    | '/reveal'
    | '/houses/$id'
    | '/houses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CircuitsRoute: typeof CircuitsRoute
  HousesRoute: typeof HousesRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  PlayRoute: typeof PlayRoute
  RevealRoute: typeof RevealRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits': {
      id: '/circuits'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof CircuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveal': {
      id: '/reveal'
      path: '/reveal'
      fullPath: '/reveal'
      preLoaderRoute: typeof RevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses/': {
      id: '/houses/'
      path: '/'
      fullPath: '/houses/'
      preLoaderRoute: typeof HousesIndexRouteImport
      parentRoute: typeof HousesRoute
    }
    '/houses/$id': {
      id: '/houses/$id'
      path: '/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof HousesIdRouteImport
      parentRoute: typeof HousesRoute
    }
  }
}

interface HousesRouteChildren {
  HousesIdRoute: typeof HousesIdRoute
  HousesIndexRoute: typeof HousesIndexRoute
}

const HousesRouteChildren: HousesRouteChildren = {
  HousesIdRoute: HousesIdRoute,
  HousesIndexRoute: HousesIndexRoute,
}

const HousesRouteWithChildren =
  HousesRoute._addFileChildren(HousesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CircuitsRoute: CircuitsRoute,
  HousesRoute: HousesRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  PlayRoute: PlayRoute,
  RevealRoute: RevealRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
